### ISSUE TITLE
tests/conftest.py is not compatible with the newest fido2 library

### ISSUE THREAD

**Issue by tsusanka** [solokeys/fido2-tests#27]
Yubico's python-fido2 [0.8.1 release](https://github.com/Yubico/python-fido2/releases) introduced some backwards-incompatible changes and fido2-tests is not compatible with it.

This commit (introduction of the changes) might help https://github.com/Yubico/python-fido2/commit/4c48977173fd32f70e61f518c7624558ffe54b9c.

cc @andrewkozlik

**Comment by jnaulty** [comment]
For those blocked by this, quick solution is just to lock the `requirements.txt` to the versions before the breaking change:
```
diff --git a/requirements.txt b/requirements.txt
index 9fb2dd2..d2c5959 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-fido2 >=0.7.3
+fido2 >=0.7.3, <0.8
 pyscard
 pytest
 pytest-ordering
```

**Comment by prusnak** [comment]
This has been fixed in master here https://github.com/solokeys/fido2-tests/commit/7881689b86a2e9ad5aa9ba2aa9c0747bd406b643
